### PR TITLE
Add a new class UniOut. and make stdout and stderr wraps with UniOut

### PR DESCRIPTION
**Pull request by timtan**
Add a UniOut class and wrap stdout and stderr.

### CODE REVIEW

**Comment by moskytw** [comment]
I did some changes after merging this and #3. If you interest in, you can just check the new _uniout.py and uniout.py. :)

**Comment by timtan** [comment]
looking better!

**Comment by moskytw** [comment]
I did lot of changes today. It has a well structure now. You may want to take a look at the newest [uniout.py](https://github.com/moskytw/uniout/blob/dev/uniout.py) and [_uniout.py](https://github.com/moskytw/uniout/blob/dev/_uniout.py). :)

**Comment by timtan** [comment]
the structure looks nice,  I keep up the new structure !

**Pull request merged**
